# Generated by Django 6.0.6 on 2026-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(help_text='Full display name shown across the platform.', max_length=80)),
                ('email', models.EmailField(help_text='Primary identifier used for login and notifications.', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Optional contact number for booking coordination.', max_length=20, null=True)),
                ('location', models.CharField(help_text='City or district used for proximity-based tool discovery.', max_length=100)),
                ('profile_image', models.ImageField(blank=True, help_text='Optional avatar displayed on profile and review cards.', null=True, upload_to='users/profiles/%Y/%m/')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Running average of all reviews received as owner or renter.', max_digits=3)),
                ('is_verified', models.BooleanField(default=False, help_text='Trust badge granted after identity confirmation.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user account is active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
