# Generated by Django 6.0.6 on 2026-07-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lahza_subaccount_code',
            field=models.CharField(blank=True, default='', help_text="Lahza subaccount code (ACCT_...) that receives this owner's payouts.", max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_account_last4',
            field=models.CharField(blank=True, default='', help_text='Last 4 digits of the payout account, for display only.', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_bank_code',
            field=models.CharField(blank=True, default='', help_text='Settlement bank code from Lahza (e.g. AIB).', max_length=20),
        ),
    ]
