"""
Django settings for rentora_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import environ
from pathlib import Path
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

sys.path.insert(0, os.path.join(BASE_DIR, 'rentora_project'))

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])

SITE_URL = env.str('SITE_URL', default='http://127.0.0.1:8000')

# Required when Django runs behind Nginx/reverse-proxy on AWS.
# Without this, build_absolute_uri() builds links with 127.0.0.1 instead of
# the real server hostname, breaking email verification and password-reset links.
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# ── Production security hardening ───────────────────────────
# Only enforced when DEBUG=False, so local development over plain
# http://127.0.0.1:8000 (and ngrok testing with DEBUG=True) keeps working.
if not DEBUG:
    SECURE_SSL_REDIRECT = True          # http:// -> https:// redirect
    SESSION_COOKIE_SECURE = True        # session cookie only sent over https
    CSRF_COOKIE_SECURE = True           # csrf cookie only sent over https
    CSRF_COOKIE_HTTPONLY = True         # JS never reads it (csrf_token is rendered server-side)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # Start small; raise once HTTPS has been stable for a while, and only add
    # includeSubDomains/preload after that — both are hard to undo site-wide.
    SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=3600)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'listings',
    'console',
]

AUTH_USER_MODEL = 'users.User'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.LastSeenMiddleware',
]

ROOT_URLCONF = 'rentora_project.rentora_project.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "rentora_project" / "templates"],
        "APP_DIRS": True,  
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "listings.context_processors.wishlist_count",
                "listings.context_processors.notification_count",
                "listings.context_processors.current_user",
                "listings.context_processors.site_settings",
                "listings.context_processors.footer_categories",
                "console.context_processors.console_counts",
            ],
        },
    }
]

WSGI_APPLICATION = 'rentora_project.rentora_project.wsgi.application'

SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default=f"mysql://{env('DB_USER')}:{env('DB_PASSWORD')}@{env('DB_HOST')}:{env('DB_PORT')}/{env('DB_NAME')}"
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('ar', 'العربية'),
]

LOCALE_PATHS = [
    BASE_DIR / 'rentora_project' / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'rentora_project' / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'rentora_project' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'rentora_project' / 'media'

LOGIN_URL = 'users:login'

# ── AI Integration ───────────────────────────────────────────
# Google Gemini Flash — free tier (15 RPM / 1M tokens per day).
# Get your key at: https://aistudio.google.com/app/apikey
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')

# ── Email ────────────────────────────────────────────────────
# Development default: prints emails to the console.
# Switch to smtp.EmailBackend and fill SMTP vars in .env for real sending.
EMAIL_BACKEND       = env('EMAIL_BACKEND',       default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST          = env('EMAIL_HOST',          default='smtp.gmail.com')
EMAIL_PORT          = env.int('EMAIL_PORT',      default=587)
EMAIL_USE_TLS       = env.bool('EMAIL_USE_TLS',  default=True)
EMAIL_HOST_USER     = env('EMAIL_HOST_USER',     default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL  = env('DEFAULT_FROM_EMAIL',  default='Rentora <noreply@rentora.ps>')


# ─────────────────────────────────────────────
#  Lahza payment gateway (Palestine)
#  Docs: https://docs.lahza.io  |  https://api-docs.lahza.io
#  Get keys from the Lahza dashboard → Settings → API Keys.
#  Use the TEST (sandbox) keys until the merchant account is approved for LIVE.
# ─────────────────────────────────────────────
LAHZA_SECRET_KEY   = env("LAHZA_SECRET_KEY",   default="")   # sk_test_... / sk_live_...
LAHZA_PUBLIC_KEY   = env("LAHZA_PUBLIC_KEY",   default="")   # pk_test_... / pk_live_...
LAHZA_WEBHOOK_SECRET = env("LAHZA_WEBHOOK_SECRET", default="")  # for verifying webhook signatures
LAHZA_API_BASE     = env("LAHZA_API_BASE",     default="https://api.lahza.io")
# 3-letter code Lahza charges in. Confirm which your account settles in (ILS / JOD / USD).
LAHZA_CURRENCY     = env("LAHZA_CURRENCY",     default="ILS")
# Platform commission taken from every rental, as a percentage (e.g. 15 = 15%).
PLATFORM_FEE_PERCENT = env.int("PLATFORM_FEE_PERCENT", default=15)

# Single source of truth for how money is DISPLAYED across the site (templates,
# emails, JS). Must stay in sync with LAHZA_CURRENCY, since that is what is
# actually charged — showing "$" while billing ILS was a real bug.
CURRENCY_CODE   = LAHZA_CURRENCY                    # 'ILS'
CURRENCY_SYMBOL = {"ILS": "₪", "JOD": "د.أ", "USD": "$"}.get(LAHZA_CURRENCY, LAHZA_CURRENCY)
