# Generated by Django 6.0.6 on 2026-07-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('suspend', 'Suspend user'), ('reinstate', 'Reinstate user'), ('dismiss_reports', 'Dismiss reports'), ('force_complete', 'Force-complete booking'), ('category_change', 'Category change'), ('resolve_dispute', 'Resolve dispute')], max_length=20),
        ),
    ]
