# Generated by Django 6.0.6 on 2026-06-24 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable category label displayed across the UI.', max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or relative asset path used in category cards.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short, descriptive name shown on listing cards.', max_length=120)),
                ('description', models.TextField(help_text='Full details: use-case, brand, accessories included, etc.')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Rental price charged per calendar day (local currency).', max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, help_text='Refundable security deposit collected before rental begins.', max_digits=10)),
                ('location', models.CharField(help_text='City or district where the tool is available for pickup.', max_length=100)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='good', help_text='Owner-declared (or AI-suggested) physical condition of the tool.', max_length=20)),
                ('is_available', models.BooleanField(default=True, help_text='Controls whether this listing appears in search results.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Top-level grouping used for discovery and filtering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='listings.category')),
                ('owner', models.ForeignKey(help_text='The platform member who owns and manages this listing.', on_delete=django.db.models.deletion.CASCADE, related_name='tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of the rental period (inclusive).')),
                ('end_date', models.DateField(help_text='Last day of the rental period (inclusive).')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Auto-calculated: rental_days × tool.daily_rate.', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Lifecycle state of this rental request.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renter', models.ForeignKey(help_text='The platform member who requested the rental.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(help_text='The tool listing this booking is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.tool')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded photo file (stored under MEDIA_ROOT).', upload_to='tools/images/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False, help_text='Marks this photo as the cover image shown on listing cards. Only one image per tool should carry this flag.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(help_text='The parent tool listing this photo belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.tool')),
            ],
            options={
                'verbose_name': 'Tool Image',
                'verbose_name_plural': 'Tool Images',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Numeric score from 1 (Poor) to 5 (Excellent).')),
                ('comment', models.TextField(blank=True, help_text='Optional written feedback (max 1000 characters).', null=True)),
                ('review_type', models.CharField(choices=[('for_tool', 'For Tool'), ('for_owner', 'For Owner'), ('for_renter', 'For Renter')], help_text='Indicates the target of this review.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(help_text='The completed booking this review is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.booking')),
                ('reviewer', models.ForeignKey(help_text='The platform member who authored this review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'reviewer', 'review_type'), name='unique_review_per_booking_reviewer_type')],
            },
        ),
    ]
