# Generated by Django 6.0.6 on 2026-06-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_add_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Lifecycle state of this rental request.', max_length=20),
        ),
    ]
