# Generated by Django 6.0.6 on 2026-06-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_add_payment_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the owner pressed Mark as Returned.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('return_pending', 'Return Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Lifecycle state of this rental request.', max_length=20),
        ),
    ]
