# Generated by Django 6.0.6 on 2026-07-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_report'),
        ('listings', '0008_add_confirmed_status'),
    ]

    operations = [
    ]
