# Generated by Django 6.0.6 on 2026-07-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_merge_0005_report_0008_add_confirmed_status'),
        ('listings', '0010_add_review_fk_to_notification'),
    ]

    operations = [
    ]
