# Generated by Django 6.0.6 on 2026-07-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_merge_20260709_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=10),
        ),
    ]
