# Generated by Django 6.0.6 on 2026-07-14 20:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_report_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, help_text='Original deposit amount from booking', max_digits=10)),
                ('initiated_by', models.CharField(choices=[('owner', 'Owner'), ('renter', 'Renter')], help_text='Who raised the dispute (Owner about damage, or Renter about false claim)', max_length=10)),
                ('reason', models.TextField(help_text="Why the dispute was initiated. Owner: 'Tool returned broken', Renter: 'Tool was already broken'")),
                ('status', models.CharField(choices=[('open', 'Open'), ('staff_reviewing', 'Staff Reviewing'), ('resolved_refund', 'Resolved - Full Refund'), ('resolved_partial', 'Resolved - Partial Refund'), ('resolved_claim', 'Resolved - Damage Claim')], default='open', max_length=20)),
                ('dispute_evidence', models.FileField(blank=True, help_text='Photo/video evidence of tool damage or condition', null=True, upload_to='disputes/%Y/%m/%d/')),
                ('owner_response', models.TextField(blank=True, help_text="Owner's response/counter-argument to the dispute")),
                ('renter_response', models.TextField(blank=True, help_text="Renter's response/counter-argument to the dispute")),
                ('staff_decision', models.CharField(blank=True, choices=[('refund_full', 'Full Refund to Renter'), ('refund_partial', 'Partial Refund to Renter'), ('owner_claim', 'Pay Owner for Damage'), ('split_50_50', '50/50 Split'), ('dismiss', 'Dismiss Claim')], help_text="Admin's resolution decision", max_length=20, null=True)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes from staff investigation')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be refunded to renter (if resolved_refund/partial)', max_digits=10, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid to owner for damage (if resolved_claim)', max_digits=10, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the dispute was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_dispute', to='listings.booking')),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Dispute',
                'verbose_name_plural': 'Deposit Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_total', models.DecimalField(decimal_places=2, help_text='rental_days × daily_rate', max_digits=10)),
                ('platform_fee_pct', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Platform commission percentage (default 15%)', max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Calculated: rental_total × (platform_fee_pct / 100)', max_digits=10)),
                ('insurance_opted', models.BooleanField(default=False)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, help_text='Optional damage protection ($10 if opted, $0 otherwise)', max_digits=10)),
                ('insurance_platform_cut', models.DecimalField(decimal_places=2, default=0, help_text='30% of insurance fee goes to platform, 70% reserved for claims', max_digits=10)),
                ('total_charged_to_renter', models.DecimalField(decimal_places=2, help_text='rental_total + insurance_fee (what Stripe charges)', max_digits=10)),
                ('owner_payout', models.DecimalField(decimal_places=2, help_text='rental_total - platform_fee (owner receives after commission)', max_digits=10)),
                ('stripe_fee_pct', models.DecimalField(decimal_places=2, default=Decimal('2.90'), help_text='Stripe percentage (2.9% + $0.30 fixed)', max_digits=5)),
                ('stripe_fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Stripe fixed fee per transaction', max_digits=5)),
                ('stripe_fee', models.DecimalField(decimal_places=2, help_text='Calculated Stripe processing fee', max_digits=10)),
                ('net_platform_revenue', models.DecimalField(decimal_places=2, help_text='platform_fee + insurance_platform_cut - stripe_fee', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(help_text='Associated booking for this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_breakdown', to='listings.booking')),
            ],
            options={
                'verbose_name': 'Payment Breakdown',
                'verbose_name_plural': 'Payment Breakdowns',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's full name", max_length=100)),
                ('email', models.EmailField(help_text="Sender's email for response", max_length=254)),
                ('subject', models.CharField(help_text='Issue subject/title', max_length=200)),
                ('category', models.CharField(choices=[('payment', 'Payment Issue'), ('booking', 'Booking Problem'), ('dispute', 'Report/Dispute'), ('feature', 'Feature Request'), ('technical', 'Technical Issue'), ('other', 'Other')], help_text='Support category for routing', max_length=20)),
                ('message', models.TextField(help_text='Full message body')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('staff_response', models.TextField(blank=True, help_text="Staff's response/resolution")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the ticket was resolved', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member handling this ticket', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_messages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Associated user if logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='listings_co_status_ced99a_idx'), models.Index(fields=['email', '-created_at'], name='listings_co_email_d0229a_idx')],
            },
        ),
    ]
