# Generated by Django 6.0.6 on 2026-07-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_depositdispute_paymentbreakdown_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_received', 'New Booking Request'), ('booking_approved', 'Booking Approved'), ('booking_rejected', 'Booking Rejected'), ('payment_received', 'Payment Received'), ('return_requested', 'Return Requested'), ('return_confirmed', 'Return Confirmed'), ('return_reminder', 'Return Reminder'), ('new_message', 'New Message'), ('new_review', 'New Review'), ('support_reply', 'Support Reply')], max_length=30),
        ),
    ]
