# Generated by Django 6.0.6 on 2026-07-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo shared in the conversation (e.g. tool condition).', null=True, upload_to='chat/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
