# Generated by Django 6.0.6 on 2026-07-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_message_image_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional evidence (photo, screenshot, document) for staff review.', null=True, upload_to='support/%Y/%m/%d/'),
        ),
    ]
