# Generated by Django 6.0.6 on 2026-07-30 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_contactmessage_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalConditionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='condition/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_photos', to='listings.booking')),
            ],
            options={
                'verbose_name': 'Rental Condition Photo',
                'verbose_name_plural': 'Rental Condition Photos',
                'ordering': ['id'],
            },
        ),
    ]
