# Generated by Django 6.0.6 on 2026-07-30 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_rentalconditionphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalconditionphoto',
            name='phase',
            field=models.CharField(choices=[('pickup', 'At pickup (renter)'), ('return', 'At return (owner)')], default='pickup', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalconditionphoto',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
