# Generated by Django 6.0.6 on 2026-07-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_rentalconditionphoto_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbreakdown',
            name='gateway_reference',
            field=models.CharField(blank=True, default='', help_text='Lahza transaction reference — used to issue refunds.', max_length=100),
        ),
    ]
